content:
  source:
    dockerfile: Dockerfile.ocp
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/configmap-reload.git
      web: https://github.com/openshift/configmap-reload
    path: ''
    ci_alignment:
      streams_prs:
        ci_build_root:
          stream: rhel-8-golang-ci-build-root
for_payload: true
from:
  builder:
  - stream: golang
  member: openshift-enterprise-base
labels:
  License: ASL 2.0
  io.k8s.description: This is a component reloads another process if a configured configmap volume is remounted.
  io.k8s.display-name: configmap reload
  io.openshift.tags: kubernetes
name: openshift/ose-configmap-reloader
owners:
- team-monitoring@redhat.com
delivery:
  delivery_repo_names:
  - openshift4/ose-configmap-reloader
