content:
  source:
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/cluster-ingress-operator.git
      web: https://github.com/openshift/cluster-ingress-operator
    ci_alignment:
      streams_prs:
        ci_build_root:
          stream: rhel-8-golang-ci-build-root
for_payload: true
from:
  builder:
  - stream: golang
  member: openshift-enterprise-base
name: openshift/ose-cluster-ingress-operator
owners:
- aos-network-edge@redhat.com
delivery:
  delivery_repo_names:
  - openshift4/ose-cluster-ingress-operator
