content:
  source:
    dockerfile: Dockerfile.rhel7
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/cluster-config-operator.git
      web: https://github.com/openshift/cluster-config-operator
for_payload: true
from:
  builder:
  - stream: golang
  member: openshift-enterprise-base
name: openshift/ose-cluster-config-operator
owners:
- aos-master@redhat.com
- tnozicka@redhat.com
delivery:
  delivery_repo_names:
  - openshift4/ose-cluster-config-operator
