content:
  source:
    dockerfile: Dockerfile
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/cloud-network-config-controller.git
      web: https://github.com/openshift/cloud-network-config-controller
for_payload: true
from:
  builder:
  - stream: golang
  member: openshift-enterprise-base
name: openshift/ose-cloud-network-config-controller
owners:
- aos-networking-staff@redhat.com
delivery:
  delivery_repo_names:
  - openshift4/cloud-network-config-controller-rhel8
