content:
  source:
    dockerfile: Dockerfile.ocp
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/k8s-prometheus-adapter.git
      web: https://github.com/openshift/k8s-prometheus-adapter
    ci_alignment:
      streams_prs:
        ci_build_root:
          stream: rhel-9-golang-ci-build-root
distgit:
  branch: rhaos-{MAJOR}.{MINOR}-rhel-9
  component: ose-prometheus-adapter-container
delivery:
  repo_name: ose-k8s-prometheus-adapter
  delivery_repo_names:
  - openshift4/ose-k8s-prometheus-adapter-rhel9
for_payload: true
from:
  builder:
  - stream: rhel-9-golang
  member: openshift-enterprise-base-rhel9
name: openshift/ose-k8s-prometheus-adapter-rhel9
payload_name: k8s-prometheus-adapter
owners:
- team-monitoring@redhat.com
