content:
  source:
    dockerfile: Dockerfile
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/cloud-network-config-controller.git
      web: https://github.com/openshift/cloud-network-config-controller
distgit:
  branch: rhaos-{MAJOR}.{MINOR}-rhel-8
  component: ose-cloud-network-config-controller-container
delivery:
  # Maps to honeybadger repo_name
  repo_name: cloud-network-config-controller
  delivery_repo_names:
  - openshift4/cloud-network-config-controller-rhel8
for_payload: true
from:
  builder:
  - stream: golang
  member: openshift-enterprise-base
name: openshift/ose-cloud-network-config-controller
payload_name: cloud-network-config-controller
owners:
- aos-networking-staff@redhat.com
