content:
  source:
    dockerfile: Dockerfile.ocp
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/prometheus-operator.git
      web: https://github.com/openshift/prometheus-operator
    path: ''
    ci_alignment:
      streams_prs:
        ci_build_root:
          stream: rhel-8-golang-ci-build-root
for_payload: true
from:
  builder:
  - stream: golang
  member: openshift-enterprise-base
labels:
  License: ASL 2.0
  io.k8s.description: This component manages the lifecycle and configuration of a Prometheus monitoring server as well as Prometheus Alertmanager clusters.
  io.k8s.display-name: Prometheus Operator
  io.openshift.tags: prometheus
name: openshift/ose-prometheus-operator
owners:
- team-monitoring@redhat.com
delivery:
  delivery_repo_names:
  - openshift4/ose-prometheus-operator
